# tool_server.py
from dataclasses import dataclass
from typing import List, Any, Callable
import random


@dataclass
class Tool:
    name: str
    func: Callable
    description: str
    input_params: dict


class ToolServer:
    def __init__(self):
        self.tools = {}
        self.register_tools()

    @staticmethod
    def gen_random(start=0, end=100):
        # Convert float to int if needed
        start = int(start)
        end = int(end)
        print(f"Generating random number between {start} and {end}")
        print("*" * 20)
        return random.randint(start, end)

    @staticmethod
    def answer_random(random: int):
        print(f"Received random number: {random}")
        print("*" * 20)
        return f"Generated random number: {random}"

    def register_tools(self):
        self.register_tool(
            "gen_random",
            self.gen_random,
            "Step 1: Generate a random number between start and end (inclusive). Use answer_random next to format the result.",
            {"start": "integer", "end": "integer"},
        )
        self.register_tool(
            "answer_random",
            self.answer_random,
            "Step 2: Format the random number generated by gen_random into a nice message.",
            {"random": "integer"},
        )

    def register_tool(
        self, name: str, func: Callable, description: str, input_params: dict
    ):
        self.tools[name] = Tool(name, func, description, input_params)

    def execute_tool(self, tool_name: str, **kwargs) -> Any:
        """Execute a tool directly by name with given arguments"""
        if tool_name not in self.tools:
            raise ValueError(f"Tool {tool_name} not found")

        tool = self.tools[tool_name]
        return tool.func(**kwargs)

    def get_tools_config(self):
        """Get tool configurations in format compatible with Gemini"""
        function_declarations = []
        for tool in self.tools.values():
            properties = {}
            for param_name, param_type in tool.input_params.items():
                properties[param_name] = {
                    "type": param_type,
                    "description": f"The {param_name} parameter for {tool.name}",
                }

            function_declarations.append(
                {
                    "name": tool.name,
                    "description": tool.description,
                    "parameters": {
                        "type": "OBJECT",
                        "properties": properties,
                        "required": list(tool.input_params.keys()),
                    },
                }
            )

        return [{"function_declarations": function_declarations}]
